import '../models/exercise_definition.dart';

class SampleDataService {
  static List<ExerciseDefinition> defaultExercises() {
    return const [
      ExerciseDefinition(
        id: 'lib_pull_up',
        name: '引体',
        category: '背',
        type: 'bodyweight',
        unit: 'reps',
      ),
      ExerciseDefinition(
        id: 'lib_neutral_pull_up',
        name: '对握引体',
        category: '背',
        type: 'bodyweight',
        unit: 'reps',
      ),
      ExerciseDefinition(
        id: 'lib_chin_up',
        name: '反手引体',
        category: '背',
        type: 'bodyweight',
        unit: 'reps',
      ),
      ExerciseDefinition(
        id: 'lib_assisted_pull_up',
        name: '辅助引体',
        category: '背',
        type: 'bodyweight',
        unit: 'reps',
      ),
      ExerciseDefinition(
        id: 'lib_lat_pulldown',
        name: '高位下拉',
        category: '背',
        type: 'weighted',
        unit: 'kg',
      ),
      ExerciseDefinition(
        id: 'lib_reverse_lat_pulldown',
        name: '反手高位下拉',
        category: '背',
        type: 'weighted',
        unit: 'kg',
      ),
      ExerciseDefinition(
        id: 'lib_barbell_row',
        name: '杠铃划船',
        category: '背',
        type: 'weighted',
        unit: 'kg',
      ),
      ExerciseDefinition(
        id: 'lib_seated_row',
        name: '坐姿水平划船',
        category: '背',
        type: 'weighted',
        unit: 'kg',
      ),
      ExerciseDefinition(
        id: 'lib_kneeling_single_row',
        name: '跪姿单边划船',
        category: '背',
        type: 'weighted',
        unit: 'kg',
        isUnilateral: true,
      ),
      ExerciseDefinition(
        id: 'lib_inverted_row',
        name: '澳式引体',
        category: '背',
        type: 'bodyweight',
        unit: 'reps',
      ),
      ExerciseDefinition(
        id: 'lib_lying_pullover',
        name: '仰卧直臂上拉',
        category: '背',
        type: 'weighted',
        unit: 'kg',
      ),
      ExerciseDefinition(
        id: 'lib_face_pull',
        name: '绳索面拉',
        category: '背',
        type: 'weighted',
        unit: 'kg',
      ),
      ExerciseDefinition(
        id: 'lib_squat',
        name: '深蹲',
        category: '腿',
        type: 'weighted',
        unit: 'kg',
      ),
      ExerciseDefinition(
        id: 'lib_smith_squat',
        name: '史密斯深蹲',
        category: '腿',
        type: 'weighted',
        unit: 'kg',
      ),
      ExerciseDefinition(
        id: 'lib_zercher_squat',
        name: '泽奇深蹲',
        category: '腿',
        type: 'weighted',
        unit: 'kg',
      ),
      ExerciseDefinition(
        id: 'lib_deadlift',
        name: '硬拉',
        category: '腿',
        type: 'weighted',
        unit: 'kg',
      ),
      ExerciseDefinition(
        id: 'lib_single_leg_deadlift',
        name: '单腿硬拉',
        category: '腿',
        type: 'weighted',
        unit: 'kg',
        isUnilateral: true,
      ),
      ExerciseDefinition(
        id: 'lib_bulgarian_split_squat',
        name: '保加利亚蹲',
        category: '腿',
        type: 'weighted',
        unit: 'kg',
        isUnilateral: true,
      ),
      ExerciseDefinition(
        id: 'lib_back_extension',
        name: '山羊挺身',
        category: '臀',
        type: 'weighted',
        unit: 'kg',
      ),
      ExerciseDefinition(
        id: 'lib_single_leg_glute_bridge',
        name: '单腿臀桥',
        category: '臀',
        type: 'bodyweight',
        unit: 'reps',
        isUnilateral: true,
      ),
      ExerciseDefinition(
        id: 'lib_spanish_squat',
        name: '西班牙蹲',
        category: '腿',
        type: 'timed',
        unit: 'sec',
      ),
      ExerciseDefinition(
        id: 'lib_mid_leg_jump',
        name: '中腿跳',
        category: '腿',
        type: 'bodyweight',
        unit: 'reps',
      ),
      ExerciseDefinition(
        id: 'lib_adductor',
        name: '内收肌',
        category: '腿',
        type: 'weighted',
        unit: 'kg',
      ),
      ExerciseDefinition(
        id: 'lib_calf_raise',
        name: '提踵',
        category: '腿',
        type: 'weighted',
        unit: 'kg',
      ),
      ExerciseDefinition(
        id: 'lib_bench_press',
        name: '卧推',
        category: '胸',
        type: 'weighted',
        unit: 'kg',
      ),
      ExerciseDefinition(
        id: 'lib_dumbbell_bench_press',
        name: '平板哑铃卧推',
        category: '胸',
        type: 'weighted',
        unit: 'kg',
      ),
      ExerciseDefinition(
        id: 'lib_alternating_dumbbell_press',
        name: '哑铃交替卧推',
        category: '胸',
        type: 'weighted',
        unit: 'kg',
      ),
      ExerciseDefinition(
        id: 'lib_machine_fly',
        name: '固定夹胸',
        category: '胸',
        type: 'weighted',
        unit: 'kg',
      ),
      ExerciseDefinition(
        id: 'lib_push_up',
        name: '俯卧撑',
        category: '胸',
        type: 'bodyweight',
        unit: 'reps',
      ),
      ExerciseDefinition(
        id: 'lib_overhead_press',
        name: '实力推',
        category: '肩',
        type: 'weighted',
        unit: 'kg',
      ),
      ExerciseDefinition(
        id: 'lib_dumbbell_shoulder_press',
        name: '哑铃推肩',
        category: '肩',
        type: 'weighted',
        unit: 'kg',
      ),
      ExerciseDefinition(
        id: 'lib_seated_dumbbell_press',
        name: '坐姿哑铃推肩',
        category: '肩',
        type: 'weighted',
        unit: 'kg',
      ),
      ExerciseDefinition(
        id: 'lib_lateral_raise',
        name: '侧平举',
        category: '肩',
        type: 'weighted',
        unit: 'kg',
      ),
      ExerciseDefinition(
        id: 'lib_cable_external_rotation',
        name: '龙门架外旋侧拉',
        category: '肩',
        type: 'weighted',
        unit: 'kg',
        isUnilateral: true,
      ),
      ExerciseDefinition(
        id: 'lib_tyw',
        name: 'TYW',
        category: '肩',
        type: 'mobility',
        unit: 'done',
      ),
      ExerciseDefinition(
        id: 'lib_dead_bug',
        name: '死虫',
        category: '核心',
        type: 'bodyweight',
        unit: 'reps',
      ),
      ExerciseDefinition(
        id: 'lib_copenhagen_plank',
        name: '哥本哈根支撑',
        category: '核心',
        type: 'timed',
        unit: 'sec',
        isUnilateral: true,
      ),
      ExerciseDefinition(
        id: 'lib_side_plank',
        name: '侧支撑',
        category: '核心',
        type: 'timed',
        unit: 'sec',
        isUnilateral: true,
      ),
      ExerciseDefinition(
        id: 'lib_cable_horizontal_push',
        name: '龙门架水平推',
        category: '核心',
        type: 'weighted',
        unit: 'kg',
        isUnilateral: true,
      ),
      ExerciseDefinition(
        id: 'lib_cable_horizontal_pull',
        name: '龙门架水平拉',
        category: '核心',
        type: 'weighted',
        unit: 'kg',
        isUnilateral: true,
      ),
      ExerciseDefinition(
        id: 'lib_woodchop',
        name: '水平伐木',
        category: '核心',
        type: 'weighted',
        unit: 'kg',
        isUnilateral: true,
      ),
      ExerciseDefinition(
        id: 'lib_kneeling_hip_flexion_plank',
        name: '跪姿屈髋平板支撑',
        category: '核心',
        type: 'timed',
        unit: 'sec',
      ),
      ExerciseDefinition(
        id: 'lib_seated_hip_flexion',
        name: '坐姿髋屈',
        category: '核心',
        type: 'bodyweight',
        unit: 'reps',
        isUnilateral: true,
      ),
      ExerciseDefinition(
        id: 'lib_single_cable_press',
        name: '绳索单侧前推',
        category: '核心',
        type: 'weighted',
        unit: 'kg',
        isUnilateral: true,
      ),
      ExerciseDefinition(
        id: 'lib_treadmill',
        name: '跑步机',
        category: '有氧',
        type: 'cardio',
        unit: 'min',
      ),
      ExerciseDefinition(
        id: 'lib_incline_walk',
        name: '爬坡',
        category: '有氧',
        type: 'cardio',
        unit: 'min',
      ),
      ExerciseDefinition(
        id: 'lib_badminton',
        name: '羽毛球',
        category: '有氧',
        type: 'cardio',
        unit: 'min',
      ),
      ExerciseDefinition(
        id: 'lib_thoracic_mobility',
        name: '胸椎灵活性',
        category: '灵活性',
        type: 'mobility',
        unit: 'done',
      ),
      ExerciseDefinition(
        id: 'lib_hip_flexor_stretch',
        name: '髋屈肌拉伸',
        category: '灵活性',
        type: 'mobility',
        unit: 'done',
        isUnilateral: true,
      ),
      ExerciseDefinition(
        id: 'lib_bird_dog',
        name: '鸟狗式',
        category: '灵活性',
        type: 'mobility',
        unit: 'reps',
        isUnilateral: true,
      ),
      ExerciseDefinition(
        id: 'lib_glute_stretch',
        name: '臀肌拉伸',
        category: '灵活性',
        type: 'mobility',
        unit: 'done',
        isUnilateral: true,
      ),
    ];
  }
}
